# Generated by Django 5.2.6 on 2026-03-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usina', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('sub_sala', models.CharField(blank=True, max_length=255, null=True)),
                ('motor', models.CharField(max_length=255)),
                ('configuracao', models.CharField(max_length=255)),
                ('arquivo', models.CharField(max_length=255)),
                ('data_arquivo', models.FloatField(blank=True, null=True)),
                ('data_convertida', models.DateTimeField()),
                ('rms', models.FloatField()),
                ('nivel1', models.FloatField()),
                ('nivel2', models.FloatField()),
            ],
        ),
    ]
