# Generated by Django 5.2.6 on 2026-03-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usina', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('sub_sala', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('configuracao', models.CharField(max_length=255)),
                ('nivel1', models.FloatField()),
                ('nivel2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_data_aviso', models.DateTimeField(blank=True, null=True)),
                ('resultado_data_manutencao', models.DateTimeField(blank=True, null=True)),
                ('manutencao_recente', models.BooleanField(default=False)),
                ('ja_bateu_no_limite', models.BooleanField(default=False)),
                ('motor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='manutencao.motor')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_arquivo', models.DateTimeField()),
                ('data_convertida', models.DateTimeField(db_index=True)),
                ('rms', models.FloatField()),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='manutencao.motor')),
            ],
            options={
                'ordering': ['-data_convertida'],
                'indexes': [models.Index(fields=['motor', 'data_convertida'], name='manutencao__motor_i_ad93ca_idx')],
            },
        ),
    ]
